// 使用隔离副本验证失败不会覆盖正式CSV，不修改玩家数据或原始工作簿。
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),core=require('./validator.cjs');
const temp=process.env.CONFIG_WORK_DIR||path.join(path.parse(root).root,'gptwork','config-export');
fs.mkdirSync(temp,{recursive:true});
const fixture=fs.mkdtempSync(path.join(temp,'regression-'));
for(const dir of ['tools/config','tools/ui','tools/art','source_assets/art','assets/resources/ui','design/tables','assets/scripts','assets/resources/config','assets/resources/audio','assets/art']) {
  const src=path.join(root,dir);if(fs.existsSync(src))fs.cpSync(src,path.join(fixture,dir),{recursive:true});
}
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
function run(){return cp.spawnSync(process.execPath,[path.join(fixture,'tools/config/export.cjs'),'--check'],{encoding:'utf8',windowsHide:true,timeout:120000});}
function digest(){return fs.readFileSync(path.join(fixture,'assets/resources/config/manifest.json'),'utf8');}
test('CSV 保留引号、逗号与换行',()=>assert.equal(core.parseCsv('id,text\r\n1,"a,b\n""c"""\r\n')[0].text,'a,b\n"c"'));
test('完整原始表与CSV一致',()=>{const r=run();assert.equal(r.status,0,r.stderr);});
const csv=path.join(fixture,'assets/resources/config/I18.csv'),originalCsv=fs.readFileSync(csv),manifest=digest();
test('手改CSV会阻止构建且不覆盖文件',()=>{fs.appendFileSync(csv,'\n');const r=run();assert.notEqual(r.status,0);assert.match(r.stderr,/CSV已过期/);assert.equal(digest(),manifest);assert.equal(fs.readFileSync(csv).length,originalCsv.length+1);fs.writeFileSync(csv,originalCsv);});
const xlsx=path.join(fixture,'design/tables/I18.xlsx'),originalXlsx=fs.readFileSync(xlsx);
test('工作簿版本改变必须重新导表',()=>{fs.appendFileSync(xlsx,Buffer.from([0]));const r=run();assert.notEqual(r.status,0);assert.match(r.stderr,/原始表格已变更/);assert.equal(digest(),manifest);fs.writeFileSync(xlsx,originalXlsx);});

// 以下只改隔离副本，验证 Prefab 构建门禁与预览同步边界。
const uiCheck=require(path.join(fixture,'tools/ui/check-prefabs.cjs')).check;
const configSources={};for(const name of core.TABLE_NAMES)configSources[name]=fs.readFileSync(path.join(fixture,'assets/resources/config',name+'.csv'),'utf8');core.installConfigs(configSources);
// 网格与地台使用相同参数，拒绝会形成错位地台或孤岛的配置。
test('格位偏离网格时拒绝配置',()=>{const lines=configSources.Spot.trim().split(/\r?\n/),cells=lines[1].split(',');cells[3]=String(Number(cells[3])+1);lines[1]=cells.join(',');assert.throws(()=>core.installConfigs({...configSources,Spot:lines.join('\n')}),/Off-grid spot/);core.installConfigs(configSources);});
test('孤立格位时拒绝配置',()=>{const lines=configSources.Spot.trim().split(/\r?\n/),cells=lines[1].split(',');cells[3]=String(Number(cells[3])+10000);lines[1]=cells.join(',');assert.throws(()=>core.installConfigs({...configSources,Spot:lines.join('\n')}),/Isolated spot/);core.installConfigs(configSources);});
test('网格间距必须为正数',()=>{const lines=configSources.Map.trim().split(/\r?\n/),fields=lines[0].split(','),cells=lines[1].split(',');cells[fields.indexOf('gridSize')]='0';lines[1]=cells.join(',');assert.throws(()=>core.installConfigs({...configSources,Map:lines.join('\n')}),/Invalid map grid/);core.installConfigs(configSources);});

test('反馈参数越界或非整数时拒绝配置',()=>{for(const [key,value] of [['impactLimit','0'],['impactLimit','1.5'],['impactLimit','129'],['hitFeedbackSeconds','0'],['hitFeedbackScale','1'],['bossEntranceSeconds','-1']]){const lines=configSources.Global.trim().split(/\r?\n/),index=lines.findIndex(line=>line.split(',')[1]===key),cells=lines[index].split(',');cells[3]=value;lines[index]=cells.join(',');assert.throws(()=>core.installConfigs({...configSources,Global:lines.join('\n')}),/Invalid feedback parameter/);}core.installConfigs(configSources);});

test('首领或结算关键节点缺失时阻止构建',()=>{for(const [key,name] of [['battle_hud','Fill'],['win','Summary']]){const file=path.join(fixture,'assets/resources/ui',key+'.prefab'),original=fs.readFileSync(file),data=JSON.parse(original);data.find(n=>n.__type__==='cc.Node'&&n._name===name)._name='Missing';fs.writeFileSync(file,JSON.stringify(data));try{assert.throws(()=>uiCheck(fixture,core),/缺少运行时节点/);}finally{fs.writeFileSync(file,original);}}});

const home=path.join(fixture,'assets/resources/ui/home.prefab'),originalHome=fs.readFileSync(home);
test('缺少预制体阻止校验',()=>{fs.renameSync(home,home+'.fixture');try{assert.throws(()=>uiCheck(fixture,core),/缺少预制体/);}finally{fs.renameSync(home+'.fixture',home);}});
test('缺少运行时绑定节点阻止校验',()=>{const d=JSON.parse(originalHome);d.find(o=>o.__type__==='cc.Node'&&o._name==='Adventure')._name='Missing';fs.writeFileSync(home,JSON.stringify(d));try{assert.throws(()=>uiCheck(fixture,core),/缺少运行时节点/);}finally{fs.writeFileSync(home,originalHome);}});
test('I18预览过期可同步且保留手工布局',()=>{const d=JSON.parse(originalHome),binding=d.find(o=>o.key==='ui.redesign.homeTitle'),label=d[d[binding.node.__id__]._components.find(ref=>d[ref.__id__].__type__==='cc.Label').__id__],expected=core.text(binding.key),node=d.find(o=>o.__type__==='cc.Node'&&o._name==='Settings');assert.ok(label);label._string='过期预览';node._lpos.x+=7;fs.writeFileSync(home,JSON.stringify(d));try{assert.throws(()=>uiCheck(fixture,core),/文字预览已过期/);uiCheck(fixture,core,true);const result=JSON.parse(fs.readFileSync(home));assert.equal(result.find(o=>o._name==='Settings')._lpos.x,node._lpos.x);assert.ok(result.some(o=>o.__type__==='cc.Label'&&o._string===expected));}finally{fs.writeFileSync(home,originalHome);}});
test('独立PNG预览过期阻止构建并可同步',()=>{const d=JSON.parse(originalHome),image=d.find(o=>o.frameKey);image.previewFrame.__uuid__="bad-frame";fs.writeFileSync(home,JSON.stringify(d));try{assert.throws(()=>uiCheck(fixture,core),/图片预览已过期/);uiCheck(fixture,core,true);assert.doesNotThrow(()=>uiCheck(fixture,core));}finally{fs.writeFileSync(home,originalHome);}});


// 进化表的引用和计时错误必须在导表阶段拦截。
function changeEvolution(table,key,field,value){const lines=configSources[table].trim().split(/\r?\n/),header=lines[0].split(','),index=lines.findIndex((line,i)=>i>0&&line.split(',')[1]===key),cells=lines[index].split(',');cells[header.indexOf(field)]=value;lines[index]=cells.join(',');return {...configSources,[table]:lines.join('\n')};}
test('进化连发周期、费用整数和减速组合非法时拒绝',()=>{for(const [key,field,value] of [['sprout_burst','burstGap','1'],['sprout_heavy','upgradeCost','1.5'],['frost_deep','slowSpeedRatio','1']])assert.throws(()=>core.installConfigs(changeEvolution('StaffBranch',key,field,value)),/Invalid/);core.installConfigs(configSources);});
test('进化攻击参数非法时拒绝',()=>{for(const [key,field,value]of [['scope_pierce','pierceRatio','2'],['spark_chain','chainCount','2.5'],['spark_chain','chainRadius','0'],['ember_scorch','burnSeconds','0'],['mint_focus','markRatio','1'],['fan_volley','shotSpeed','0'],['fan_spread','shotColor','bad']])assert.throws(()=>core.installConfigs(changeEvolution('StaffBranch',key,field,value)),/Invalid/);core.installConfigs(configSources);});
test('进化形态归属、图片缺失和排序重复时拒绝',()=>{for(const [key,field,value]of [['sprout_heavy','branchKey','frost_deep'],['sprout_heavy','battleImageKey','missing'],['sprout_burst','displayOrder','1']])assert.throws(()=>core.installConfigs(changeEvolution('StaffForm',key,field,value)),/mismatch|Missing|Duplicate/);core.installConfigs(configSources);});
test('进化卡与图鉴缩略图缺失时阻止构建',()=>{for(const [key,name]of [['evolution_card','Summary'],['detail','Base1']]){const file=path.join(fixture,'assets/resources/ui',key+'.prefab'),original=fs.readFileSync(file),d=JSON.parse(original);d.find(n=>n.__type__==='cc.Node'&&n._name===name)._name='Missing';fs.writeFileSync(file,JSON.stringify(d));try{assert.throws(()=>uiCheck(fixture,core),/缺少运行时节点/);}finally{fs.writeFileSync(file,original);}}});

function changeLoadout(table,id,field,value){const records=core.parseCsv(configSources[table]),keys=Object.keys(records[0]);records.find(r=>r.id===String(id))[field]=value;const escape=v=>/[",\n\r]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;return {...configSources,[table]:[keys.join(','),...records.map(r=>keys.map(k=>escape(r[k])).join(','))].join('\n')};}
test('配队拒绝重复、提前解锁与超量默认阵容',()=>{for(const [id,field,value]of [[8,'candidateStaff','sprout|sprout'],[4,'candidateStaff','sprout|frost|bloom|fan'],[8,'defaultStaff','sprout|frost|bloom|scope|spark'],[8,'defaultStaff','fan|frost|bloom|scope'],[8,'slots','4.5']])assert.throws(()=>core.installConfigs(changeLoadout('LevelLoadout',id,field,value)),/loadout|Loadout/);core.installConfigs(configSources);});
test('店员解锁关、定位文本与排序必须有效',()=>{for(const [id,field,value]of [[1,'unlockLevel','99'],[1,'roleKey','missing'],[2,'displayOrder','1']])assert.throws(()=>core.installConfigs(changeLoadout('Staff',id,field,value)),/reference|order/);core.installConfigs(configSources);});
test('配队逐关规则不可缺失或重复',()=>{const records=core.parseCsv(configSources.LevelLoadout),keys=Object.keys(records[0]),source=[keys.join(','),...records.slice(1).map(r=>keys.map(k=>r[k]).join(','))].join('\n');assert.throws(()=>core.installConfigs({...configSources,LevelLoadout:source}),/loadout/);assert.throws(()=>core.installConfigs(changeLoadout('LevelLoadout',2,'levelId','1')),/loadout/);core.installConfigs(configSources);});
test('配队卡和预告节点缺失时阻止构建',()=>{for(const [key,name]of [['loadout','Start'],['loadout_card','Info'],['wave_preview','Cards'],['enemy_preview_card','Count']]){const file=path.join(fixture,'assets/resources/ui',key+'.prefab'),original=fs.readFileSync(file),d=JSON.parse(original);d.find(n=>n.__type__==='cc.Node'&&n._name===name)._name='Missing';fs.writeFileSync(file,JSON.stringify(d));try{assert.throws(()=>uiCheck(fixture,core),/缺少运行时节点/);}finally{fs.writeFileSync(file,original);}}});

test('挑战候选时间、奖励与首领倍率配置错误时阻止构建',()=>{for(const [table,id,field,value]of [['ChallengeRule',1,'choiceWaves','0|1|1'],['ChallengeRule',1,'choiceWaves','0|15'],['ChallengeRule',1,'adRefreshPerChoice','-1'],['ChallengeRule',1,'minIntervalRatio','0'],['ChallengeRule',1,'reviveProgress','1'],['Wave',2105,'bossHealthScale','0']])assert.throws(()=>core.installConfigs(changeLoadout(table,id,field,value)));core.installConfigs(configSources);});
test('强化参数缺字段、类型错误、负阈值与错误引用被拒绝',()=>{for(const [id,field,value]of [[1,'params','{"every":3}'],[1,'params','{"every":0,"shots":3,"ratio":0.7}'],[1,'params','{"every":3,"shots":3,"ratio":"0.7"}'],[1,'staffKey','missing'],[1,'iconKey','missing'],[1,'iconKey','perk_S02'],[25,'exclusive','E01']])assert.throws(()=>core.installConfigs(changeLoadout('ChallengePerk',id,field,value)));core.installConfigs(configSources);});
test('挑战界面和卡牌缺少绑定时阻止构建',()=>{for(const [key,name]of [['challenge_pick','Refresh'],['challenge_card','Description']]){const file=path.join(fixture,'assets/resources/ui',key+'.prefab'),original=fs.readFileSync(file),d=JSON.parse(original);d.find(n=>n.__type__==='cc.Node'&&n._name===name)._name='Missing';fs.writeFileSync(file,JSON.stringify(d));try{assert.throws(()=>uiCheck(fixture,core),/缺少运行时节点/);}finally{fs.writeFileSync(file,original);}}});
const code=path.join(fixture,'assets/scripts/config/ConfigTables.ts');
test('商品图鉴拒绝缺失文案、图片与非法解锁关',()=>{for(const [field,value]of [['nameKey','missing'],['imageKey','missing'],['unlockLevel','21']])assert.throws(()=>core.installConfigs(changeLoadout('Goods',1,field,value)));core.installConfigs(configSources);});
test('未同步校验器会阻止导出',()=>{fs.appendFileSync(code,'\n');const r=run();assert.notEqual(r.status,0);assert.match(r.stderr,/配置校验器已修改/);assert.equal(digest(),manifest);});
test('原生布局被修改或漏配节点时阻止构建',()=>{const apply=require('../ui/config-layout.cjs').apply,d=JSON.parse(originalHome);d.find(n=>n.__type__==='cc.Node'&&n._name==='Settings')._lpos.x+=7;fs.writeFileSync(home,JSON.stringify(d));try{assert.throws(()=>apply(fixture,core,false),/UI布局已过期/);apply(fixture,core,true);assert.doesNotThrow(()=>apply(fixture,core,false));}finally{fs.writeFileSync(home,originalHome);}const rows=core.rows.bind(core);try{core.rows=n=>n==='UiLayout'?rows(n).filter(r=>r.key!=='home:Settings'):rows(n);assert.throws(()=>apply(fixture,core,false),/缺少原始布局配置/);}finally{core.rows=rows;}});
console.log(passed+'项通过；隔离证据：'+fixture);
