/* 用户2026-10-07新版UI的可重复美术布局更新；保留运行时绑定路径和已有meta。 */
const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'../..'),dir=root+'/assets/resources/ui',source=root+'/source_assets/art/production/ui_redesign_20261007';const templates=JSON.parse(fs.readFileSync(dir+'/home.prefab','utf8'));const clone=x=>structuredClone(x),byType=t=>templates.find(o=>o.__type__===t),textTemplate=templates.find(o=>o.key&&!o.image),skinTemplate=templates.find(o=>o.image&&o.key),imageTemplate=templates.find(o=>o.frameKey);let skins;
class Prefab{
 constructor(name,base=name){this.name=name;this.a=JSON.parse(fs.readFileSync(dir+'/'+base+'.prefab','utf8'));this.a[0]._name=name;this.a[1]._name=name;}
 n(p){let n=this.a[1];if(!p)return n;for(const k of p.split('/')){n=n._children.map(r=>this.a[r.__id__]).find(o=>o._name===k);if(!n)throw Error(this.name+'/'+p);}return n;}
 ix(n){return this.a.indexOf(n);}components(n){return n._components.map(r=>this.a[r.__id__]);}t(n){return this.components(n).find(o=>o.__type__==='cc.UITransform');}l(p){return this.components(this.n(p)).find(o=>o.__type__==='cc.Label');}
 component(n,template){let o=clone(template);o.node={__id__:this.ix(n)};let c={__type__:'cc.CompPrefabInfo',fileId:crypto.randomUUID().replaceAll('-','').slice(0,22)};o.__prefab={__id__:this.a.length+1};n._components.push({__id__:this.a.length});this.a.push(o,c);return o;}
 add(parent,name,x,y,w,h){const host=typeof parent==='string'?this.n(parent):parent,n=clone(byType('cc.Node'));Object.assign(n,{_name:name,_parent:{__id__:this.ix(host)},_children:[],_components:[],_active:true,_prefab:{__id__:this.a.length+1}});n._lpos={__type__:'cc.Vec3',x,y,z:0};n._lscale={__type__:'cc.Vec3',x:1,y:1,z:1};host._children.push({__id__:this.a.length});this.a.push(n,{__type__:'cc.PrefabInfo',root:{__id__:1},asset:{__id__:0},fileId:crypto.randomUUID().replaceAll('-','').slice(0,22)});const t=this.component(n,byType('cc.UITransform'));t._contentSize={__type__:'cc.Size',width:w,height:h};return n;}
 skinNode(parent,name,key,x,y,w,h){const n=this.add(parent,name,x,y,w,h),img=this.add(n,'Artwork',0,0,w,h),sp=this.component(img,byType('cc.Sprite'));sp._color={__type__:'cc.Color',r:255,g:255,b:255,a:255};sp._spriteFrame=null;const s=this.component(n,skinTemplate);s.key=key;s.padding=0;s.image={__id__:this.ix(img)};s.previewFrame={__uuid__:this.skinUuid(key),__expectedType__:'cc.SpriteFrame'};return n;}
 skinUuid(key){const row=skins.find(r=>r.key===key);if(!row)throw Error('缺少皮肤'+key);return JSON.parse(fs.readFileSync(root+'/assets/art/'+row.path.replace('/spriteFrame','.png')+'.meta','utf8')).uuid+'@f9941';}
 label(parent,name,key,x,y,w,h,size,color='#5c3020'){const n=this.add(parent,name,x,y,w,h),l=this.component(n,byType('cc.Label'));l._string='';l._fontSize=size;l._actualFontSize=size;l._lineHeight=size+5;l._overflow=2;l._isBold=true;l._color=this.color(color);if(key){const t=this.component(n,textTemplate);t.key=key;}return n;}
 color(hex){return{__type__:'cc.Color',r:parseInt(hex.slice(1,3),16),g:parseInt(hex.slice(3,5),16),b:parseInt(hex.slice(5,7),16),a:255};}
 move(p,x,y,w,h){const n=this.n(p);n._lpos.x=x;n._lpos.y=y;if(w!=null)this.t(n)._contentSize.width=w;if(h!=null)this.t(n)._contentSize.height=h;return n;}
 hide(...paths){for(const p of paths)this.n(p)._active=false;}
 font(p,size,color='#5c3020'){const l=this.l(p);if(!l)return;l._fontSize=size;l._actualFontSize=size;l._lineHeight=size+5;l._isBold=true;l._color=this.color(color);}
 paint(p,key){const n=this.n(p),s=this.components(n).find(o=>o.image&&o.key);if(!s){this.skinNode(n,'NewSkin',key,0,0,this.t(n)._contentSize.width,this.t(n)._contentSize.height);return;}s.key=key;s.padding=0;s.previewFrame={__uuid__:this.skinUuid(key),__expectedType__:'cc.SpriteFrame'};const sp=this.components(this.a[s.image.__id__]).find(o=>o.__type__==='cc.Sprite');sp._color=this.color('#ffffff');}
 icon(parent,name,key,x,y,w,h){const r=skins.find(r=>r.key===key),scale=Math.min(w/r.width,h/r.height);return this.skinNode(parent,name,key,x,y,r.width*scale,r.height*scale);}
 button(p,key='button_green'){const n=this.n(p);for(const r of n._children){const c=this.a[r.__id__];if(['Shadow','Outline','Highlight','Accent'].includes(c._name))c._active=false;}if(n._children.some(r=>this.a[r.__id__]._name==='Surface'))this.paint(p+'/Surface',key);if(n._children.some(r=>this.a[r.__id__]._name==='Disabled'))this.paint(p+'/Disabled','button_disabled');}
 key(p,key){const n=this.n(p),t=this.components(n).find(o=>o.key&&!o.image);if(t)t.key=key;else this.component(n,{...textTemplate,key});}
 save(){for(const l of this.a.filter(o=>o.__type__==='cc.Label'))if(l._color.r===255&&l._color.g===255&&l._color.b===255){l._enableOutline=true;l._outlineColor=this.color('#6a3925');l._outlineWidth=1.4;}fs.writeFileSync(dir+'/'+this.name+'.prefab',JSON.stringify(this.a,null,2)+'\n');if(!fs.existsSync(dir+'/'+this.name+'.prefab.meta')){const m=JSON.parse(fs.readFileSync(dir+'/home.prefab.meta'));m.uuid=crypto.randomUUID();fs.writeFileSync(dir+'/'+this.name+'.prefab.meta',JSON.stringify(m,null,2)+'\n');}}
}
function generic(p){for(const n of p.a.filter(o=>o.__type__==='cc.Node')){if(n._name==='Shadow')n._active=false;const s=p.components(n).find(o=>o.image&&o.key);if(s&&n._name!=='Dim'&&s.key.startsWith('round_')&&p.t(n)._contentSize.width>35&&p.t(n)._contentSize.height>22){const name=n._name,parent=p.a[n._parent?.__id__],key=name==='Disabled'?'button_disabled':name==='Surface'&&(parent?._name?.includes('Level')||parent?._name?.includes('Base'))?'tab_selected':name==='Surface'&&parent&&['Primary','Start','Refresh','Adventure','Challenge','Upgrade'].includes(parent._name)?'button_gold':name==='Surface'&&parent&&['Secondary','Home','Close','Back','Default','Previous','Next'].includes(parent._name)?'button_green':'window_cream';s.key=key;s.padding=0;s.previewFrame={__uuid__:p.skinUuid(key),__expectedType__:'cc.SpriteFrame'};p.components(p.a[s.image.__id__]).find(o=>o.__type__==='cc.Sprite')._color=p.color('#ffffff');}const l=p.components(n).find(o=>o.__type__==='cc.Label');if(l){l._color=p.color('#5c3020');l._isBold=true;}}
}

module.exports={Prefab,setSkins:rows=>{skins=rows;}};
